name: CD

on:
  push:
    branches:
      - main

jobs:
  push_to_registries:
    name: Push image to registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: clapclapexcitement
          password: ${{ secrets.DOCKER_HUB_LOGIN }}
          repository: clapclapexcitement/dind-ansible-molecule
          tag_with_ref: true
          tags: latest
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: mdb
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: mdb/dind-ansible-molecule
          tag_with_ref: true
          tags: latest
