name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    name: Build and test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Test
        run: make test

  push-ref:
    name: Push image ref tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: clapclapexcitement
          password: ${{ secrets.DOCKER_HUB_LOGIN }}
          repository: clapclapexcitement/dind-ansible-molecule
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: mdb
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: mdb/dind-ansible-molecule
          tag_with_ref: true
