name: CI

on:
  push:
   branches-ignore:
    - main

jobs:
  build:
    name: Build image

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make
